name: AwasmCloud Build
description: Build an AwasmCloud apps
author: AwasmCloud
inputs:
  region:
    description: AwasmCloud region name
    required: true
  app:
    description: AwasmCloud app name
    required: true
  description:
    description: AwasmCloud build description
    required: false
  cached:
    description: Whether to utilise the docker cache during the build
    required: false
    default: true
outputs:
  release:
    description: Release ID of the created build
runs:
  using: docker
  image: Dockerfile
